0no-co/wonka

- .index.js
- bsconfig.json
- package.json
- yarn.lock
This PR:
- adds `@glennsl/bs-jest` (and removes `bs-jest`, the NPM package has moved to `@glennsl/bs-jest`: https://github.com/glennsl/bs-jest#bs-jest)
- removes `bs-loader` (`bs-loader` is currently in the maintenance mode: https://github.com/reasonml-community/bs-loader)
- runs tests correctly (using `bs-loader` and `jest` leads to the following error: https://travis-ci.org/kitten/wonka/jobs/384749376#L534)
> Run tests correctly

- __tests__/wonka_test.re
This PR adds some basic tests for `makeSubject`, based off both [`callbag-subject` tests](https://github.com/staltz/callbag-subject/blob/master/test.js) and [RxJS Subject tests](https://github.com/ReactiveX/rxjs/blob/master/spec/Subject-spec.ts). There's likely still some way to go, but I wanted to take an initial stab and at least see if I was grokking this concept correctly. Let me know what I can improve on @kitten, loving Wonka thus far!
> Add basic tests for Subject.

- __tests__/wonka_test.re
- package.json
- src/operators/wonka_operator_concatMap.rei
- src/operators/wonka_operator_filter.rei
- src/operators/wonka_operator_map.rei
- src/operators/wonka_operator_mergeMap.rei
- src/operators/wonka_operator_onEnd.rei
- src/operators/wonka_operator_onPush.rei
- src/operators/wonka_operator_onStart.rei
- src/operators/wonka_operator_scan.rei
- src/operators/wonka_operator_skipWhile.rei
- src/operators/wonka_operator_switchMap.rei
- src/operators/wonka_operator_takeWhile.rei
- src/sinks/wonka_sink_subscribe.rei
- src/sources/wonka_source_make.rei
- src/sources/wonka_source_primitives.rei
- src/web/wonka_operator_debounce.rei
- src/web/wonka_operator_throttle.rei
- src/web/wonka_source_fromListener.rei
This PR adds tests for some of the timing operators included in the `WonkaJs` module, specifically `delay`, `throttle`, `debounce`, and `sample`. Just chipping away at test coverage and having fun learning more `wonka` / observable-based programming 😅.
It also adds `*.rei` files to our pre-commit hook and `yarn refmt` script, which I missed in #15 😞.
> Add tests for WonkaJs timing functions.

- __tests__/wonka_test.re
A very smol PR to verify the behavior of `toPromise` with basic sources (i.e. `fromValue` and `fromList`). @kitten I don't think I'm quite hitting the behavior we are over on `urql` with `client.executeQuery`, but I at least wanted to get this going to verify that `toPromise` is indeed resolving values.
> Add basic tests cases for toPromise.

- bsconfig.json
Fixes #25. 
With the addition of `namespace: true` in v3, BuckleScript automatically namespaced our `Wonka` under the `Wonka` namespace. This meant that, in order to reference functions from the library in Reason, you'd have to do one of the following.
1. `open` Wonka and then use `Wonka.` for access.
```reason
open Wonka;
let source = Wonka.fromArray([|1, 2, 3|]);
```
or 2. `open Wonka.Wonka`
```reason
open Wonka.Wonka;
let source = fromArray([|1, 2, 3|]);
```
Since the module structure we use already implements namespacing manually via `wonka.ml`, we can safely remove the `namespace` field from `bsconfig.json`. This may necessitate a minor version bump since it would be a breaking change for people currently hacking around this with one of the above solutions.
> Remove namespacing from bsconfig.json. Update version in bsconfig.json.

- src/wonka_operators.re
- src/wonka_operators.test.ts
The `takeWhile` operator has a small bug that causes it to emit two `Start` signals.
One option to fix this was to keep the `sink(. Start` wrapper and remove the forwarding of the `Start` signal from the parent source, but removing it seems to still pass all compliance tests, which means that it's also just safe to remove it and save some bytes 🌶
> Fix takeWhile emitting two Start signals

- src/wonka_operators.re
- src/wonka_operators.test.ts
Fix cases where `take` is called with `<= 0` as the `max` number.
Also fix the `passesSinkClose` case where after `take` has ended, an `End` signal would still be forwarded due to some confusion with `state.taken`
> Fix take operator not supporting take(0) and not respecting Close

- src/web/wonkaJs.re
- src/wonka_operators.test.ts
This fixes the delay operator by removing an unnecessary
End event being sent when Close is received.
It also fixes a potential duplicate End signal and renames
`gotEndSignal` to `ended`.
> Fix passesSinkClose for delay operator

- src/web/wonkaJs.re
- src/wonka_operators.test.ts
Since there was no difference between `End` and `Close` in the `debounce` operator, after the timeout completed it would emit an `End` event even if the source has received `Close`. This was because in the `Push` timeout it just checks `state.ended` (or previously `gotEndSignal^`), which would also be set to `true` by `Close`.
This also adds a test to verify that the `End` signal comes in delayed after the debounce completes.
> Fix debounce emitting End after Close signal

- src/wonka_operators.re
- src/wonka_operators.test.ts
When two sources are passed two combine of which
one is hot (actively sends Push signals without Pull
talkback signals) and one is cold (only sends Push
signals with Pull talkback signals) the combine
operator stalls.
It will receive a value from the hot source, but
wait for the cold source's value forever.
To prevent this, when no Pull talkback signal has
been received, one is sent to the other (presumably cold)
source proactively.
> Fix combine for mixed cold/hot sources

- src/wonka_operators.re
- src/wonka_operators.test.ts
All of the flattening map operators weren't respecting pulls on cold sources. More care needs to go into when a flattening map operator can pull on the source or on inner sources to prevent overflowing (infinite pulls from either inner sources or the outer source) or double pulling.
> Fix cold sources for {concat,switch,merge}Map

- src/wonka_operators.re
- src/wonka_operators.test.ts
The `sample` operator needs to be modified to respect cold source pulling and pull only when it runs out of values. Additionally it needs to pull from the notifier when new values come in from the source or when the notifier is activated, see #51   for a similar fix.
Lastly this also fixes the strict ending edge cases
> Fix sample operator pulling for cold sources

- src/wonka_operators.re
- src/wonka_operators.test.ts
This is similar to #51 in that `skipUntil` wasn't pulling at consistent times. It's a little different, since the `notifier` in `skipUntil` must always be pulled first, before the `source`, since otherwise the notifier doesn't have a chance to emit a value and let `source` values flow through before `source` emits its own value.
Additionally the `skipUntil` operator now closes the `source` when it can never emit a value anymore, i.e. when the `notifier` ends without emitting any values.
> Fix skipUntil pulling and add early closing

- src/wonka_operators.re
- src/wonka_operators.test.ts
- src/wonka_sources.re
This removes Close/End guards that prevent signals after closing/ending from operators that have non-idempotent effects or only deal with a single source and instead adds guardds to all sources to make this case less likely.
> Remove redundant Close/End guards from operators and add them to sources

- src/wonka_operators.re
- src/wonka_operators.test.ts
- src/wonka_sinks.test.ts
- src/wonka_sources.re
- src/wonka_sources.test.ts
Some operators _omit_ `Push` signals until an appropriate time to send them and also have inner sources that are being pulled at the same time.
This can cause a condition where cold sources aren't being pulled anymore as the sink is not receiving a value that it can react to with a `Pull` signal.
> Fix operators that may stall when cold sources aren't receiving Pull signals

- src/wonka_operators.re
- src/wonka_operators.test.ts
Since these are side-effects that may be used
to reinsert more signals into the source chain,
through subjects for instance, they need to
protect themselves from dangerous signal loops.
> Add strict ending to onEnd and onPush

- src/Wonka_operators.re
This is technically incorrect, but a lot of asynchronous
sources will Push eagerly, which means Start doesn't
always get to talk first.
> Fix switchMap and concatMap not forwarding Push before Start

- docs/api/sources.md
Fix fromDomEvent example so compiles.
```ocaml
This has type:
option(Dom.element)
But somewhere wanted:
Dom.element (defined as
Dom.eventTarget_like(Dom._node(Dom._element(Dom._baseClass))))
```
> Fix fromDomEvent example so compiles.

- docs/api/operators.md
- add a note mentioning that `tap` is just an alias for `onPush` operator
> Add tap alias to onPush documentation

- package.json
In webpack@5, `exports` field is supported so an extra export is needed for rescript user to consume this lib
> Update package.json to support webpack@5

- src/__tests__/sources.test.ts
- src/sources.ts
This basically just cleans up the implementation of some common sources to be derived from `make`. This is basically to save on some bytes in the resulting bundle, delete duplicate functionality, and to recombine some old sources into less maintainable code.
- `makeSubject` has been replaced with `make` + `share`
- `interval` is `make`-based now
- `fromDomEvent` is `make`-based now
- `fromPromise` is `make`-based now and its timing has been fixed (delayed using `Promise.resolve`)
> chore: Derive common Wonka sources from make source

- perf/package.json
- perf/suite.js
- perf/yarn.lock
- src/__tests__/sources.test.ts
- src/sources.ts
This implements a new `fromIterable` function, supporting both iterables (iterators) and async iterables. These will likely become very useful in combination with generators and async generators in JS, as a lot of complex logic _can_ be abstracted using generators, but generators fail at abstracting a couple of complex pieces of logic easily.
I'm currently not sure this is a worthwhile addition. While it does give some performance up (which to be fair, is negligible) it does add a new host of potential features.
> feat: Implement fromIterable and replace fromArray

- rollup.config.js
Fixed an error where the Path in the source map specified the wrong location and could not be opened.
We would be happy to merge it in if you would like.
> Error opening source map

- src/observable.ts
One of the issues users may run into in the current situation is that if Wonka is loaded after other Observable objects have already been created with the **pony**fill method, Wonka will polyfill the `Symbol.observable` causing packages to no longer recognise previously created observables, breaking interoperability.
This PR makes sure Wonka's behaviour matches that of other packages like [RxJS src/internal/symbol/observable.ts](https://github.com/ReactiveX/rxjs/blob/6fa819beb91ba99dadd6262d6c13f7ddfd9470c5/src/internal/symbol/observable.ts) and [redux src/utils/symbol-observable.ts](https://github.com/reduxjs/redux/blob/cf5043a4de63cb3a26dfb5e7e2d5a68d2d8a79f5/src/utils/symbol-observable.ts).
> Use a ponyfill observable instead of polyfilling

- .changeset/eleven-candles-rest.md
- src/sinks.ts
Add missing `Promise.resolve(value).then(...)` tick to the `toPromise` helper, as has been done in `@urql/core`.
> fix: Add missing Promise.resolve() tick to toPromise

- .changeset/beige-worms-help.md
- src/__tests__/sinks.test.ts
- src/sinks.ts
This implements a `toAsyncIterable` helper, as per the ECMAScript spec and protocol. The return `AsyncIterable` creates an `AsyncIterator` when `[Symbol.asyncIterator]` is called, as per the spec.
This supersedes #125
> feat: Implement toAsyncIterable

- .changeset/new-feet-sell.md
- package.json
- pnpm-lock.yaml
- src/index.ts
- src/observable.ts
- tsconfig.json
Resolve #5814
This adds changes missing related to:
- the `Observable` typings changes,
- the isolated const enums,
- and changes how the bundled typings are generated
> fix: Add Symbol.observable typings and isolate const enums

- .changeset/khaki-lemons-argue.md
- src/__tests__/operators.test.ts
- src/operators.ts
Resolves #148 
This adds a missing overload for `filter` which will allow us to narrow types, e.g. by applying type conditions. We can now specify narrowing types and still get the desired output without casting:
```ts
pipe(
fromArray([false, true, false, true]),
filter((x): x is true => !!x),
forEach(console.log), // always true
);
> fix: Add missing filter overload to allow for type narrowing

- .changeset/five-rules-bow.md
- src/observable.ts
Thank you for creating a great lightweight library.
I have fixed the difference between [proposal-observable](https://github.com/tc39/proposal-observable#observable) and the closed type in subscription.
The following are subscription types for proposal-observable.
```typescript
interface Subscription {
// Cancels the subscription
unsubscribe() : void;
// A boolean value indicating whether the subscription is closed
get closed() : Boolean;
}
```
Current wonka subscription type.
```typescript
interface ObservableSubscription {
/** A boolean flag indicating whether the subscription is closed.
* @remarks
* When `true`, the subscription will not issue new values to the {@link ObservableObserver} and
* has terminated. No new values are expected.
*
* @readonly
*/
closed?: boolean;
/** Cancels …
```
> fix: subscription closed does not comply with proposal

- .changeset/rich-pans-smoke.md
- src/__tests__/operators.test.ts
- src/operators.ts
I realised this is impossible to express without a `takeUntil` and `share` operator, but is sometimes pretty handy, e.g. to say "take values until predicate returns false, but include the ending value".
This adds an `addOne?: boolean` argument to `takeWhile` which allows the first value that fails the predicate to also be issued on the output `Source` rather than being omitted.
This comes in handy for GraphQL’s incremental results, e.g. to express `takeWhile(result => !!result.hasNext)`. This is important, since the first result in GraphQL may pass `!hasNext` but will still contain new `data`. It's also, while implied in the spec, not guaranteed that the last `result` with `hasNext: false` won't carry a new result.
- Add an `addOne` argument to `takeWhile`
> feat: Add an addOne argument to takeWhile

- .changeset/light-cougars-enjoy.md
- src/types.d.ts
Resolves #158
- Fix missing `declare` keyword on ambient enums in `types.d.ts`
> fix: Fix missing declare keyword on ambient enums

- docs/api/sinks.md
> fix(docs): return value of `subscribe` is an object

- .changeset/yellow-hounds-heal.md
- src/__tests__/sinks.test.ts
- src/helpers.ts
- src/observable.ts
- src/sinks.ts
- src/sources.ts
- src/types.d.ts
This replaces `Symbol.asyncIterator` with a polyfill implementation, similar to `Symbol.observable`. It also refactor `toAsyncIterable` to return an object implementing both the `AsyncIterator` and `AsyncIterable` shape.
This change should improve compatibility with async iterator polyfills, specifically Babel transpilations, since it won't require the `Symbol.asyncIterator` polyfill to be included manually and can deal with how async iterable code is transpiled by Babel, specifically for the Hermes engine in React Native.
- Update `toAsyncIterable` to also implement `AsyncIterator` shape
- Add `asyncIteratorSymbol` polyfill to helpers
- Move `observableSymbol` to helpers
> fix: Improve compatibility of AsyncIterable helpers for polyfills (Babel/Hermes related)

- .changeset/fresh-tips-yell.md
- src/helpers.ts
- src/observable.ts
Resolves #167
This moves back the global `Symbol.observable` declaration to ensure that `rollup-plugin-dts` outputs it in the built typings. This also adds a note to ensure it stays intact.
- Move `Symbol.observable` declaration back to exported `observable.ts`
> fix: Add missing Symbol.observable typings to build output

- src/sources.ts
This fix eliminates the possibility of a runtime error in environments without native support for `Symbol.asyncIterator` and async generators.  In these environments it's likely Symbol.asyncIterator is not defined.
Babel regenerator that transforms the source to support async generators falls back to "@@asyncIterator" when Symbol.asyncIterator is not available. 
https://github.com/facebook/regenerator/blob/main/packages/runtime/runtime.js#L17
The fix is to use the existing "asyncIteratorSymbol" helper in Wonka to return the symbol for asynIterator, which accounts for filled-in support.
> use asyncIteratorSymbol helper to check for async Iterator
